
name: fullstack pipeline

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: codebyafroj
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [client,server]
  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.app }}/package-lock.json

      - run: npm ci
        working-directory: ${{ matrix.app }}
      - run: npm run test || echo "no test found"
        working-directory: ${{ matrix.app }}

  # lint:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       app: [client,server]
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #         cache-dependency-path: ${{ matrix.app }}/package-lock.json

  #     - run: npm ci
  #       working-directory:  ${{ matrix.app }}

  #     - run: npm run lint
  #       working-directory: ${{ matrix.app }}

  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3


  #     - name: Login to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build & Push Frontend
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: client
  #         file: client/Dockerfile
  #         push: true
  #         tags: ghcr.io/${{ env.OWNER }}/frontend:${{ env.IMAGE_TAG }}

  #     - name: Build & Push Backend
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: server
  #         file: server/Dockerfile
  #         push: true
  #         tags: ghcr.io/${{ env.OWNER }}/backend:${{ env.IMAGE_TAG }}


  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: client
          file: client/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.OWNER }}/frontend:${{ env.IMAGE_TAG }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ env.OWNER }}/backend:${{ env.IMAGE_TAG }}

  update-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Update frontend image tag
        run: |
          sed -i \
          "s|image: ghcr.io/${{ env.OWNER }}/frontend:.*|image: ghcr.io/${{ env.OWNER }}/frontend:${{ env.IMAGE_TAG }}|" \
          kubernetes/frontend-deployment.yaml

      - name: Update backend image tag
        run: |
          sed -i \
          "s|image: ghcr.io/${{ env.OWNER }}/backend:.*|image: ghcr.io/${{ env.OWNER }}/backend:${{ env.IMAGE_TAG }}|" \
          kubernetes/backend-deployment.yaml

      - name: Commit and push Kubernetes changes
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add kubernetes/frontend-deployment.yaml kubernetes/backend-deployment.yaml
          git commit -m "Deploy frontend & backend images ($IMAGE_TAG)"
          git push
